<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE squad [
    <!ELEMENT squad (name?, email?, web?, picture?, title?, member+)>
    <!ATTLIST squad nick CDATA #REQUIRED>
    <!ELEMENT member (name?, email?, icq?, rank?)>
    <!ATTLIST member id CDATA #REQUIRED nick CDATA #REQUIRED>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT icq (#PCDATA)>
    <!ELEMENT web (#PCDATA)>
    <!ELEMENT picture (#PCDATA)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT rank (#PCDATA)>
]>
<squad nick="Zulu">
    <name>1 Patrol</name>
    <email>info@zulusquadron.co.uk</email>
    <web>https://zulusquadron.co.uk/</web>
    <picture></picture>
    <title>1 Patrol</title>
    <member id="76561198011403318" nick="D. Mills">
        <name>D. Mills</name>
        <email>R1C</email>
        <icq>Gunner</icq>
        <rank>Tpr</rank>
    </member>
</squad>